### PR TITLE
Fix support for `default` argument of Entity:get()

### PR DESCRIPTION
**Pull request by ghost**
Depends on #13.

### CODE REVIEW

**Comment by metasoarous** [comment]
Have you tested to see if this works as intended? I suspect that it doesn't due to the way that it's implemented so that `get` is implemented in terms of `__getitem__`, and in turn how `__getitem__` does not raise that exception anywhere, and may just be returning an empty list if it doesn't find anything. I haven't checked this yet, but am looking at #14.

**Comment by ghost** [comment]
So how should this be implemented correctly?

**Comment by devurandom** [comment]
I implemented #30 as another approach on how to fix this.

**Comment by devurandom** [comment]
This should be closed as it was obsoleted by #30, which was merged.

**Comment by metasoarous** [comment]
OK; Closing now. Thanks @devurandom!

**Pull request closed without merging**
